version: 0.2

phases:
  pre_build:
    commands:
      - echo Updating...
      - sudo apt-get update -y
      - echo Installing Docker...
      - sudo apt-get install -y docker.io
      - echo Starting the Docker service...
      - sudo service docker start
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t fastApi .

artifacts:
  files:
    - Dockerfile
    - main.py
    - requirements.txt
  base-directory: /