version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Updating...
      - sudo apt-get update -y
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t fastApi .

artifacts:
  files:
    - Dockerfile
    - main.py
    - requirements.txt
  base-directory: /