version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - echo "Pre Build started on `date`"
      - echo "Updating system"
      - apt-get update
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the code"
      - python3 -m pip install --upgrade pip
      - pip install -r requirements.txt
      - uvicorn main:app --reload
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    -  main.py
    -  requirements.txt

    
